services:
    david63.cookiepolicy.listener:
        class: david63\cookiepolicy\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@log'
            - '@controller.helper'
            - '@request'
        tags:
            - { name: event.listener }

    david63.cookiepolicy.main.controller:
        class: david63\cookiepolicy\controller\main_controller
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@language'

    david63.cookiepolicy.admin.controller:
        class: david63\cookiepolicy\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
